#!/usr/bin/env bash

# First Check who is running the commands
user_check=$( id -u )
if [ $user_check -ne 0 ]; then
  echo -n -e "\e[31m Run as root user \e[0m"
  exit 2
fi

# creating a log file named Log to store all o/p generated by command
log=/tmp/roboshop.log
rm -f $log

status_check(){
  if [ $1 -eq 0 ]; then
    echo  -e "\n\t \t \e[32m....... Done\e[0m \n"
  else
    echo  -e "\n \t \t \e[33m....... Error had encountered check log file: $log for more details\e[0m \n"
  fi
}