#!/usr/bin/env bash

# First Check who is running the commands
user_check=$( id -u )
if [ $user_check -ne 0 ]; then
  echo -n -e "\e[32mRun as root user\e[32m"
  exit 2
fi

# creating a log file named Log to store all o/p generated by command
log=/tmp/roboshop.log
rm -f $log

status_check(){
  if [ $1 -eq 0 ]; then
    echo -n -e "\e[32mDone\e[0m \n"
  else
    echo -n -e "\e[32mError had encountered check log file: $log for more details\e[0m \n"
  fi
}