#!/usr/bin/env bash

source common.sh


echo  "Installing Nginx .... "

status=$( yum install nginx -y &>> $log)

echo  "Enabling  Nginx .... "

status=$( systemctl enable nginx &>> $log)

echo  "Starting Nginx .... "

status=$( systemctl start nginx &>> $log )


