#!/usr/bin/env bash

source common.sh

echo  "Installing Nginx .... "

status=$( yum install nginx -y )

echo  "Enabling  Nginx .... "

status=$( systemctl enable nginx )

echo  "Starting Nginx .... "

status=$( systemctl start nginx )
